### ISSUE TITLE
Replace deprecated models

### ISSUE THREAD

**Issue by benman1** [benman1/generative_ai_with_langchain#14]
The following models have been deprecated on January 4th by OpenAI:
* text-ada-001
* text-babbage-001
* text-curie-001
* text-davinci-001
* text-davinci-002
* text-davinci-003
* davinci-instruct-beta
* curie-instruct-beta
* code-search-ada-code-001
* code-search-ada-text-001
* code-search-babbage-code-001
* code-search-babbage-text-001
* text-search-ada-doc-001
* text-search-ada-query-001
* text-search-babbage-doc-001
* text-search-babbage-query-001
* text-search-curie-doc-001
* text-search-curie-query-001
* text-search-davinci-doc-001
* text-search-davinci-query-001
* text-similarity-ada-001
* text-similarity-babbage-001
* text-similarity-curie-001
* text-similarity-davinci-001
* text-davinci-edit-001
* code-davinci-edit-001
* text-davinci-insert-001
* text-davinci-insert-002

If any of these models are mentioned in the code, they should be replaced by models that are [still available](https://platform.openai.com/docs/models/continuous-model-upgrades).

**Comment by theAfricanQuant** [comment]
Hello @benman1 
This list is very helpful

Thanks for sharing

**Comment by benman1** [comment]
Hi Ricky, @theAfricanQuant! Let me know if you find things that don't work or need updating. I am not always able to make it work on the same day, but I'll try to help as soon as I can.

**Comment by theAfricanQuant** [comment]
You are doing just fine @benman1

**Comment by theAfricanQuant** [comment]
![image](https://github.com/benman1/generative_ai_with_langchain/assets/33702921/a79b3d09-27d8-41c3-b4b7-ea5dcd3512c8)
