### ISSUE TITLE
Docker Setup Command

### ISSUE THREAD

**Issue by insculptor** [benman1/generative_ai_with_langchain#15]
Books  Errata:

Chapter 3 Setting up Docker:
Build the Docker image from the Dockerfile in this repository:
docker build -t langchain_ai 

This should be

Build the Docker image from the Dockerfile in this repository:
docker build -t langchain_ai .

(Add .)

**Comment by benman1** [comment]
Thanks, @insculptor! I sometimes forget the dot. I'll ask the book editor to correct this!
