### ISSUE TITLE
Add python dev tools to linux system requirements. 

### ISSUE THREAD

**Issue by Convalytics** [benman1/generative_ai_with_langchain#18]
I was having issues installing requirements.txt on Ubuntu 22 and had to install python dev tools and build essentials to resolve. 

`sudo apt install python3-dev
sudo apt-get install build-essential -y
`
For python dev tools, you might need to install the package specific to your python version. 
`sudo apt install python3.11-dev`

**Comment by benman1** [comment]
Hi @Convalytics; That's strange. Are you installing this directly on your system? The yaml file specifies Python 3.10.

**Comment by benman1** [comment]
Closing as stale
