### ISSUE TITLE
Replicate Example not working in Chapter 3

### ISSUE THREAD

**Issue by elmondhir** [benman1/generative_ai_with_langchain#23]
While running the following Replicate Example in LangChain:

Here is a simple example for creating an image:

`from langchain.llms import Replicate`

`text2image = Replicate(`
`model="stability-ai/stable-diffusion:db21e45d3f7023abc2a46ee38a23973f6dce16bb082a930b0c49861f96d1e5bf",`
`input={"image_dimensions": "512x512"},)`

`image_url = text2image("a book cover for a book about creating generative ai applications in Python") `

I get the following error:
`Traceback (most recent call last):`
  `File "C:\Users\Azus\Desktop\GenerativeAI_LangChain\examples\test.py", line 15, in <module>`
 `   image_url = text2image("a book cover for a book about creating generative  ai applications in Python")`
`  File "C:\Users\Azus\anaconda3\envs\langchain\lib\site-packages\langchain\llms\base.py", line 825, in __call__`
`    self.generate(`
`  File "C:\Users\Azus\anaconda3\envs\langchain\lib\site-packages\langchain\llms\base.py", line 621, in generate`
`    output = self._generate_helper(`
`  File "C:\Users\Azus\anaconda3\envs\langchain\lib\site-packages\langchain\llms\base.py", line 523, in _generate_helper`
`    raise e`
`  File "C:\Users\Azus\anaconda3\envs\langchain\lib\site-packages\langchain\llms\base.py", line 510, in _generate_helper`
`    self._generate(`
`  File "C:\Users\Azus\anaconda3\envs\langchain\lib\site-packages\langchain\llms\base.py", line 1000, in _generate`
`    self._call(prompt, stop=stop, run_manager=run_manager, **kwargs)`
`  File "C:\Users\Azus\anaconda3\envs\langchain\lib\site-packages\langchain\llms\replicate.py", line 115, in _call`
`    version = model.versions.get(version_str)`
`  File "C:\Users\Azus\anaconda3\envs\langchain\lib\site-packages\replicate\version.py", line 62, in get`
`    resp = self._client._request(`
`  File "C:\Users\Azus\anaconda3\envs\langchain\lib\site-packages\replicate\client.py", line 85, in _request`
`    _raise_for_status(resp)`
`  File "C:\Users\Azus\anaconda3\envs\langchain\lib\site-packages\replicate\client.py", line 358, in _raise_for_status`
`    raise ReplicateError(resp.json()["detail"])`
`replicate.exceptions.ReplicateError: Not found.`

**Comment by elmondhir** [comment]
Nevermind i fixed the issue, it seems the model name (the long hash after `stability-ai/stable-diffusion:` ) needed to be updated, i used the one in the most recent Langchain documentation. Can you close the issue pls. 

Thanks

**Comment by benman1** [comment]
Hi @elmondhir! Thanks for highlighting the issue! Good that you figured it out! Please continue posting - it might help other people who deal with the same problems.

**Comment by brzaz228** [comment]
- @elmondhir can you please post the code you were talking about. What was the fix? Updated how?

**Comment by elmondhir** [comment]
@brzaz228 The code is in chapter 3, in the example for image generation:

`from langchain.llms import Replicate

text2image = Replicate(
model="stability-ai/stable-diffusion:db21e45d3f7023abc2a46ee38a23973f6dce16bb082a930b0c49861f96d1e5bf",
input={"image_dimensions": "512x512"},)

image_url = text2image("a book cover for a book about creating generative ai applications in Python") `

you need to change the long hash after `stability-ai/stable-diffusion:`

**Comment by benman1** [comment]
Thanks, @elmondhir!
