### ISSUE TITLE
from langchain.llms import FakeLLM in python throws an error

### ISSUE THREAD

**Issue by rkchaganti** [benman1/generative_ai_with_langchain#28]
Using Python 3.10.12 (main, Jul  5 2023, 15:02:25) [Clang 14.0.6 ] on darwin 

"from langchain.llms import FakeLLM" in python prompt throws the following error
ImportError: cannot import name 'FakeLLM' from 'langchain.llms'

**Comment by benman1** [comment]
Hi @rkchaganti. Is this an example from the book? I can't find it in the repo. There's not a lot to go by, unfortunately. Are you referring to `pandasai.llm.fake.FakeLLM`. I am closing this. Please feel free to re-open once you've posted more context.

**Comment by rkchaganti** [comment]
Thanks @brzaz228 for pointing out the page # in the book. Yes, when I try to import FakeLLM with "from langchain.llms import FakeLLM" in Python, it throws an error - **"ImportError: cannot import name 'FakeLLM' from 'langchain.llms' (<my home dir>/miniconda3/envs/langchain_ai/lib/python3.10/site-packages/langchain/llms/__init__.py)"**

I am using conda environment and executed the following:
$conda env create --file langchain_ai.yaml
$conda activate langchain_ai
$python
Python 3.10.12 (main, Jul  5 2023, 15:02:25) [Clang 14.0.6 ] on darwin

**Comment by srgonzalezz** [comment]
Hello, @rkchaganti and @brzaz228 , as dosubot responded in [this issue](https://github.com/langchain-ai/langchain/discussions/17769#discussioncomment-8523826) _"it seems like you're trying to import a class named 'LLM' from the 'langchain.llms' module"_ 

The correct class is just the one specified in the code block just below:
`from langchain.llms.fake import FakeListLLM`

This can be corroborated by [LangChain's official documentation](https://js.langchain.com/v0.1/docs/integrations/llms/fake/).
