### ISSUE TITLE
python_repl not found error

### ISSUE THREAD

**Issue by rkchaganti** [benman1/generative_ai_with_langchain#29]
When trying the following code block in Python, throws the following error:

File "<stdin>", line 1, in <module>
  File "<my home dir>/miniconda3/envs/langchain_ai/lib/python3.10/site-packages/langchain/agents/load_tools.py", line 614, in load_tools
    raise ValueError(f"Got unknown tool {name}")
ValueError: Got unknown tool python_repl

**Comment by benman1** [comment]
@rkchaganti sorry for not getting back earlier. The message is a bit cryptic without context, unfortunately. If you can provide a bit more information about what you are trying to run this would be helpful.

**Comment by benman1** [comment]
I am closing this. I am not very good at guessing. Please feel free to re-open once you've posted more context.

**Comment by SheldonLiu0412** [comment]
> I am closing this. I am not very good at guessing. Please feel free to re-open once you've posted more context.

from langchain_openai import ChatOpenAI
from langchain.agents import load_tools, initialize_agent, AgentType
from langchain_experimental.tools import PythonREPLTool
llm = ChatOpenAI()
tools = load_tools(["python_repl"])
agent = initialize_agent(tools, llm, agent=AgentType.ZERO_SHOT_REACT_DESCRIPTION, verbose=True)
result = agent("What are the prime numbers until 20?")
print(result)

line 614, in load_tools
raise ValueError(f"Got unknown tool {name}")
ValueError: Got unknown tool python_repl

**Comment by benman1** [comment]
@SheldonLiu0412 I've just searched for PythonREPLTool. It's in the data science notebook, here: https://github.com/benman1/generative_ai_with_langchain/blob/a88326e69210146adf5b9a60fbf12b6dd2d328e5/notebooks/data_science.ipynb#L109 - but the code looks different. 

Could you please specify your LC version? `pip show langchain`?

**Comment by SheldonLiu0412** [comment]
**LC Version: 0.1.14,Currently I am changing my code to：**
from langchain_openai import ChatOpenAI
from langchain.agents import initialize_agent, AgentType
from langchain_experimental.tools import PythonREPLTool
llm = ChatOpenAI()
tools = PythonREPLTool(),
agent = initialize_agent(tools, llm, agent=AgentType.ZERO_SHOT_REACT_DESCRIPTION, verbose=True)
result = agent.invoke("What are the prime numbers until 20?")
print(result)
**It works，I don't know if I'm doing the right thing**

**Comment by benman1** [comment]
Please note that the code and the book refer to LC version [0.0258](https://github.com/benman1/generative_ai_with_langchain/blob/main/requirements.txt#L3C22-L3C29). Because LC is changing so heavily, if you are using different versions the code will not work without modifications. The code that you are using should work, but is deprecated for version 0.2.

**Comment by SheldonLiu0412** [comment]
**I changed the latest code：**
from langchain import hub
from langchain.agents import AgentExecutor
from langchain_experimental.tools import PythonREPLTool
tools = [PythonREPLTool()]
from langchain.agents import create_openai_functions_agent
from langchain_openai import ChatOpenAI
instructions = """You are an agent designed to write and execute python code to answer questions.
You have access to a python REPL, which you can use to execute python code.
If you get an error, debug your code and try again.
Only use the output of your code to answer the question. 
You might know the answer without running any code, but you should still run the code to get the answer.
If it does not seem like you can write code to answer the question, just return "I don't know" as the answer.
"""
base_prompt = hub.pull("langchain-ai/openai-functions-template")
prompt = base_prompt.partial(instructions=instructions)
agent = create_openai_functions_agent(ChatOpenAI(), tools, prompt)
agent_executor = AgentExecutor(agent=agent, tools=tools, verbose=True)
result = agent_executor.invoke({"input":"What are the prime numbers until 20?"})
print(result)
**Maybe it can run in version 0.2,The change of version brought many minor problems,Thank you for your timely answer and help. Thank you again**

**Comment by benman1** [comment]
@SheldonLiu0412 no problem! I am very happy that you found the solution! It's indeed a big change in some cases to the latest version. BTW, I've created a [new branch](https://github.com/benman1/generative_ai_with_langchain/tree/softupdate) for the 0.1 version that I am updating now - it's work in progress; I am just working on chapter 5.

<img width="154" alt="image" src="https://github.com/benman1/generative_ai_with_langchain/assets/10786684/8ec2f99b-511b-4393-8d4f-de60898206b3">
