### ISSUE TITLE
Pydantic format error

### ISSUE THREAD

**Issue by CSalle** [benman1/generative_ai_with_langchain#30]
Hi,

While trying to run the Openresume CV example, I am getting the following error:

"RuntimeError: no validator found for <class '__main__.Resume'>, see `arbitrary_types_allowed` in Config"

I managed to perform a small hack by enabling arbitrary types as a decorator on top of each class (@pydantic.dataclasses.dataclass(config=Config), where Config is a class that sets arbitrary_types_allowed = True). However this seems to run into parsing errors where the data type is not correct. 

Any ideas? Thanks in advance!

**Comment by benman1** [comment]
Hi, @CSalle! That's interesting. I've just run the example and, for me, it ran fine. I did a quick search and it seems that this is pydantic's way of saying the input doesn't conform. 

Maybe the model doesn't give the expected output? Are you using a different model?
```
    llm = ChatOpenAI(model_name="gpt-3.5-turbo")
```
This is the model in the code. Is this what you are using? Have you tried other models?

**Comment by CSalle** [comment]
Hi Ben,

Thanks for getting back. After some hours of trying stuff, downgrading the version of Pydantic to 1.10 did the trick.
I was using Pydantic 2 and it seems this runs into some issues.

After that, I didn't even need the arbitrary_types_allowed trick.

Thanks a lot, I'll close the issue :)

**Comment by benman1** [comment]
Good to hear, @CSalle! Thanks for updating. FYI - my version of pydantic is 1.10.13.
