### ISSUE TITLE
ModuleNotFoundError: No module named 'chat_with_retrieval'     in chat_with_documents.py

### ISSUE THREAD

**Issue by WilsonAmadeoPerez** [benman1/generative_ai_with_langchain#33]
When I run in the console: streamlit run chat_with_retrieval/chat_with_documents.py

i got this error messge: ModuleNotFoundError: No module named 'chat_with_retrieval'

**Comment by benman1** [comment]
Hi @WilsonAmadeoPerez! That's a new one. Could you please let me know your langchain version? `pip show langchain`? 

Thanks!
Ben

**Comment by CSalle** [comment]
Can you try and check what happens when you add a __init__.py file to the chat_with_retrieval directory? It can be an empty python script

**Comment by benman1** [comment]
@WilsonAmadeoPerez @CSalle's advice is much better, please ignore mine.

**Comment by WilsonAmadeoPerez** [comment]
Thanks @CSalle and @benman1 for your answers:

1.the langchain version is: Version: 0.1.12
2. I added the the __init__.py file to the chat_with_retrieval directory. The error message is still: ModuleNotFoundError: No module named 'chat_with_retrieval'

**Comment by benman1** [comment]
Thanks a lot, @CSalle!
