### ISSUE TITLE
Summarizing texts : working alternative for ChatOpenAI

### ISSUE THREAD

**Issue by amscosta** [benman1/generative_ai_with_langchain#41]
Hi,
Can you suggest an working alternative for the summarize texts example given in your book, instead of 
using ChatOpenAI?

**Comment by amscosta** [comment]
Using non paid LLMs, of course.

**Comment by benman1** [comment]
@amscosta sorry for being late to the party. There are lots of exciting new free LLMs coming out all the time like Llama3, for example. A good way to find the best LLM is searching on HuggingFace or checking on the leaderboard. The new version of the huggingface leaderboard is even better: https://huggingface.co/spaces/open-llm-leaderboard/open_llm_leaderboard
