### ISSUE TITLE
Problem with installing dependencies with poetry

### ISSUE THREAD

**Issue by smartding** [benman1/generative_ai_with_langchain#60]
**Describe the problem**
When I try to install dependencies with `poetry install`, I get a poetry error, and no dependency is installed.

**To Reproduce**
1. clone this git repo
2. Run `poetry install` in the root directory of the repo
3. See error

**Expected behavior**
Should install all the dependencies specified in `requirements.txt`

**Error**
No dependency is installed, and the error message from poetry is:

```
The Poetry configuration is invalid:
  - Additional properties are not allowed ('dynamic' was unexpected)
```

**Software environment (please complete the following information):**
 - OS: Arch Linux
 - Python version: 3.12.5
 - Poetry version: 1.8.3

**Additional context**

**Comment by benman1** [comment]
@smartding thanks for raising the issue. 

This might be related to the poetry version. You possibly have an older version of poetry. Could you check which version you are using, please, and let me know? 

You can do
```bash
poetry --version
```

**Comment by smartding** [comment]
Thank you for your reply.

My poetry version is 1.8.3. 

It's pretty update-to-date, may be too update-to-date?

**Comment by benman1** [comment]
Interesting, thanks for checking. I hadn't tested this for a while, tbh. Going through the poetry repository and documentation, and I can't find dynamic metadata for dependencies with Poetry - this works with [setuptools](https://github.com/pypa/setuptools/blob/v62.6.0/CHANGES.rst#changes), but seems to be a missing feature in Poetry. 

I've changed the dependency setup for Poetry (just pushed). I think this might mess it up for pip/setuptools, but I'll fix that later ;). Please let me know if this works. I've just run it for myself. Thanks again for reporting.

**Comment by smartding** [comment]
Hi @benman1, your first commit ed32bf07e49c986d6064bed3bee64647cdf82d57 works, I can install all dependencies with `poetry install`. 

But the latest commit 316075fb5b96a22d6be4aacdd99eede2f6e67fd8 on the `softupdate` branch doesn't work, I got the following error when running `poetry install`:

```
The Poetry configuration is invalid:
  - The fields ['authors', 'description', 'name', 'version'] are required in package mode.
```

**Comment by benman1** [comment]
Hi @smartding. Thanks for the feedback. Good to hear it's working.

It's a shame - it seems that you can't have the pip installation and the poetry installation working. When I change back to ed32bf0, I get this with pip
```bash
      ValueError: invalid pyproject.toml config: `project`.
      configuration error: `project` must contain ['name'] properties
```
Anyway, I've reverted to the previous changes. Thanks again! I am closing this now.
