### ISSUE TITLE
No module named 'config'

### ISSUE THREAD

**Issue by bsurendar0418** [benman1/generative_ai_with_langchain#7]
1)when running streamlit run chat_with_retrieval/app.py, getting error
ModuleNotFoundError: No module named 'config'

2) could you please provide details how to run/test the programs?

**Comment by benman1** [comment]
Hi @bsurendar0418!
Yes, that's explained in chapter 3 of the book. Following best practices regarding safety, I am not committing my credentials to github. The `config.py` file, which is not included in the repository, has a method `set_environment()` that sets all the keys as environment variables like this:

Example config.py:
```bash
import os

def set_environment():
     os.environ['OPENAI_API_KEY']='your-api-key-here'
````

Obviously, you'd put your API credentials here.

Hope this helps.

**Comment by benman1** [comment]
Closing this. I've merged the explanations into the Readme.

**Comment by bsurendar0418** [comment]
Thanks Ben and team
