### ISSUE TITLE
When I run docker run -it new_image, without any reponse

### ISSUE THREAD

**Issue by scq000** [benman1/generative_ai_with_langchain#8]
<img width="541" alt="image" src="https://github.com/benman1/generative_ai_with_langchain/assets/12999391/32126151-4cf1-4fbb-ac84-9b07a786ae3a">
And when I open http://localhost:8080， it also cannot be access.

**Comment by benman1** [comment]
Hi @scq000, thanks for reporting, @danrosher thanks for coming up with something that works. the notebook directory and the change to the docker run command were key - thanks for that. I've updated the README and the Dockerfile accordingly. Also, your tag name, `langchain_ai`, is clearly better than my `new_image` ;)
