### ISSUE TITLE
Issue with Conda create env command

### ISSUE THREAD

**Issue by raghunemani** [benman1/generative_ai_with_langchain#9]
I get the following error when  I am trying to create Conda Env:

(base) C:\Users\rnema\Downloads\generative_ai_with_langchain-main>conda env create --file langchain_ai.yaml --force
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound:
  - readline=8.2
  - ncurses=6.4

I am using Anaconda on Windows 11. I have the Anconda Command Prompt as an Administrator.

**Comment by benman1** [comment]
Hi @raghunemani! Thanks for reporting this. I've just looked this up. You are right: [readline is not available for Windows](https://anaconda.org/anaconda/readline), same for [ncurses](https://anaconda.org/anaconda/ncurses). I don't have a Windows system currently that I could use for testing - have you tried taking out these two requirements, just deleting the two lines that mention ncurses and readline?
